=== LizaSav/EPAM-HW/Module9/src/main/resources/HomeLibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        targetNamespace="http://www.module9.org/HomeLibrary"
        xmlns:tns="http://www.module9.org/HomeLibrary"
        xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
    <element name="mylibrary">
        <complexType>
            <sequence>
                <element name="book"  type="tns:BookType"  maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="BookType">
        <sequence>
            <element name="title" type="string"/>
            <element name="author" type="tns:PersonType"/>
            <element name="year" type="tns:YearType" />
            <element name="format" type="tns:FormatType"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="PersonType">
           <sequence>
               <element name="firstname" type="string"/>
               <element name="lastname" type="string"/>
           </sequence>
    </complexType>

    <simpleType name="YearType">
        <restriction base="integer">
            <minInclusive value="1000"/>
        </restriction>
    </simpleType>
    
    <simpleType name="FormatType">
               <restriction base="string">
                   <enumeration value="S"/>
                   <enumeration value="M"/>
                   <enumeration value="L"/>
               </restriction>
    </simpleType>
</schema>

=== LizaSav/EPAM-HW/Module9/src/main/resources/HomeLibrary.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mylibrary xmlns="http://www.module9.org/HomeLibrary"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.module9.org/HomeLibrary HomeLibrary.xsd ">
    <book id="1">
        <title>Naively.Super</title>
        <author>
            <firstname>Erlend</firstname>
            <lastname>Lu</lastname>
        </author>
        <year>2010</year>
        <format>S</format>
    </book>
    <book id="2">
        <title>The Great Gatsby</title>
        <author>
            <firstname>Francis Scott</firstname>
            <lastname>Fitzgerald</lastname>
        </author>
        <year>2013</year>
        <format>M</format>
    </book>
    <book id="3">
        <title>The Castle</title>
        <author>
            <firstname>Franz</firstname>
            <lastname>Kafka</lastname>
        </author>
        <year>2010</year>
        <format>S</format>
    </book>
</mylibrary>
